name: Array Input test

on:
  push:
    branches:
      - main

jobs:
  with_ref:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: testtest
        uses: ./.github/actions/input-array
        with:
          ensure: a, b, c
