name: Main pushed

on:
  - workflow_dispatch
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  write_push:
    name: Logging commit event
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: logging push commit
        run: |
          echo '${{ toJSON(github.event) }}'

          related_prs=$(curl -sL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.event.repository.full_name }}/commits/${{ github.event.head_commit.id }}/pulls)
          echo "${related_prs}"
          pr_url=$(echo $related_prs | jq '. | map(select(.state="open"))[0].html_url')

          echo '{
                  "Repository": "${{ github.event.repository.full_name }}",
                  "CommitSha": "${{ github.event.head_commit.id }}",
                  "CommittedAt": "'"${timestamp}"'",
                  "AuthorGithubName": "${{ github.event.pusher.name }}",
                  "Message": "${{ github.event.commits[0].message }}",
                  "Link": {"S": "'"${pr_url}"'"},
                }'
