name: Commit checkout test

on:
  push:
    branches:
      - main

jobs:
  with_ref:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: branch check
        run: |
          target_sha=417c7ecf794c902e23e6eba0fbf85aa82fe75f70

          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/commits/${target_sha}/branches-where-head
