name: Main pushed

on:
  push:
    branches:
      - main

jobs:
  some-test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
    steps:
      - name: Mimic test
        run: |
          echo "test in shard ${{ matrix.shard }}"

  check-success:
    name: check-success
    needs: [some-test]
    runs-on: ubuntu-latest
    steps:
      - name: Mimic test
        run: |
          echo "Yey!"
